### ISSUE TITLE
Support SDK retry in case of rate limit

### ISSUE THREAD

**Issue by alexluong** [hookdeck/terraform-provider-hookdeck#108]
## Problem

There are customers with enough resources to run into Hookdeck API rate limit (240rqm) which blocks their Terraform flow. We should use Fern's SDK [retries with backoff](https://buildwithfern.com/learn/sdks/features/retries-with-backoff) feature to make sure we're not a blocking the Terraform run here.

## API

I suggest we allow 2 ways to configure the retry max attempts:

1: via environment variable `HOOKDECK_SDK_MAX_ATTEMPTS`
2: via option

```terraform
provider "hookdeck" {
  api_key = var.hookdeck_api_key
  sdk_max_attempts = 5
}
```

**Comment by leggetter** [comment]
Blocked by https://github.com/hookdeck/terraform-provider-hookdeck/issues/109

**Comment by leggetter** [comment]
v0.6.0 of the Go SDK has been released with the latest version of the Fern Go generator.

We next need to complete #109, which will unblock this and a number of other features/PRs.
