### ISSUE TITLE
Add region and service AWS destination auth config

### ISSUE THREAD

**Issue by leggetter** [hookdeck/terraform-provider-hookdeck#117]
Work in progress: https://github.com/hookdeck/terraform-provider-hookdeck/pull/116

## Docs

https://hookdeck.com/docs/api#update-a-destination#update-a-destination

<img width="681" alt="CleanShot 2024-10-21 at 20 57 23@2x" src="https://github.com/user-attachments/assets/944ef840-9a7e-4fa9-96f9-28899b84312d">

## Dashboard

<img width="791" alt="CleanShot 2024-10-21 at 21 35 13@2x" src="https://github.com/user-attachments/assets/49332f21-c5fd-4154-b741-4ba6890dd623">

**Comment by alexluong** [comment]
Hey @leggetter, just wondering how I can take this on. It seems the codegen is working but the SDK is not fully updated?

**Comment by leggetter** [comment]
@alexluong I've updated the codegen to use the API spec in source control to ensure that all assets are based of off content in source control. This has stopped the codegen failing.

The current Go SDK release does support `service` and `region`.

See https://github.com/hookdeck/terraform-provider-hookdeck/pull/116

**Comment by alexluong** [comment]
Makes sense, in that case it seems you can take it from here, right?

**Comment by leggetter** [comment]
> Makes sense, in that case it seems you can take it from here, right?

if you have a mo, I could do with a review of #116 to see why the output seems to skip the `region` and `service`.

**Comment by leggetter** [comment]
Fixed in https://github.com/hookdeck/terraform-provider-hookdeck/pull/116
