### ISSUE TITLE
Add AWS Signature (SigV4) destination authentication

### ISSUE THREAD

**Issue by alexbouchardd** [hookdeck/terraform-provider-hookdeck#49]
A new destination authentication `AWS_SIGNATURE` has been added to the API and needs to be supported in through the provider

<img width="908" alt="Screenshot 2024-05-05 at 3 57 54 PM" src="https://github.com/hookdeck/terraform-provider-hookdeck/assets/2049224/6a508a58-d198-4b8f-847f-a97b005f2c9b">

**Comment by leggetter** [comment]
Will get this added to https://github.com/hookdeck/terraform-provider-hookdeck/pull/48
