### ISSUE TITLE
Expose response in hookdeck_webhook_registration

### ISSUE THREAD

**Issue by lijok** [hookdeck/terraform-provider-hookdeck#82]
Lots of webhook sources generate the secret for you when you register a webhook. By exposing the response in the hookdeck_webhook_registration resource, it will allow us to utilize it for more sources

**Comment by alexluong** [comment]
Hi @lijok, the response is already exposed. Can you take a look at our guide, specifically this section? https://registry.terraform.io/providers/hookdeck/hookdeck/latest/docs/guides/register-external-webhooks#use-webhook-secret-to-verify-with-hookdeck

Example code snippet:

```tf
resource "hookdeck_source_verification" "stripe_verification" {
  source_id = hookdeck_source.stripe.id
  verification = {
    stripe = {
      webhook_secret_key = jsondecode(webhook_registration.stripe.register.response).body.secret
    }
  }
}
```

**Comment by lijok** [comment]
Oh sweet. I was looking at this https://registry.terraform.io/providers/hookdeck/hookdeck/latest/docs/resources/webhook_registration which is missing the "additional attributes" section.
