### ISSUE TITLE
Add data sources

### ISSUE THREAD

**Issue by lijok** [hookdeck/terraform-provider-hookdeck#84]
Would be very useful to have access to data sources like hookdeck_destination

**Comment by lijok** [comment]
> Hi @lijok, thanks for the suggestion. I just want to make sure I understand you correctly, you'd like to use data source instead of resource because you don't want Terraform to manage the destination, just use its data in other resources, right?

No, we just need to be able to resolve the resource attributes in another stack.
I might deploy a destination in one terraform stack and need to reference its ID in another - i would do that by using a data source to resolve it by name, so I can get its ID
Same concept as in any other TF provider e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

**Comment by alexluong** [comment]
Gotcha, thanks for the clarification @lijok!

**Comment by leggetter** [comment]
@lijok v0.4.0 has just been released with support for data sources with Hookdeck Source, Destination, and Connection resources https://github.com/hookdeck/terraform-provider-hookdeck/releases/tag/v0.4.0

We'd appreciate your feedback on this when you have a moment.

Thanks to @alexluong for shipping 🚢 🐿️
